<a href="https://colab.research.google.com/github/abhisam/PadhAI_Notebooks/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy


In [0]:
import numpy as np

In [0]:
# Creating numpy array
x = np.array([1,2,3])

In [3]:
print(x)

[1 2 3]


In [4]:
type(x)

numpy.ndarray

In [0]:
# Creating array from list

l = [1,2,3,4]

x = np.asarray(l)

In [6]:
print(x)

type(x)


[1 2 3 4]


numpy.ndarray

In [0]:
x = np.asarray(l,float)

In [8]:
print(x)

print(type(x))

[1. 2. 3. 4.]
<class 'numpy.ndarray'>


In [9]:
x.shape # prints columns 

(4,)

In [0]:
# Creating two dimentional array

a = np.array([[1,2,3],[4,5,6]])


In [11]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
a[0] # prinitng first dimension

array([1, 2, 3])

In [13]:
a[1] # second dimension

array([4, 5, 6])

In [14]:
a[0,0]

1

In [15]:
a[0,1]

2

In [16]:
a[0,0:2]

array([1, 2])

In [17]:
a[1,0:2]

array([4, 5])

In [18]:
 # sub array
  
  a[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [19]:
# zeros arrays

np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
# identity matrix

np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [0]:
# normal distributed random values between zero and one

x = np.random.random((4,5))

In [22]:
print(x)

[[0.3474321  0.55340535 0.12314722 0.51713876 0.45539885]
 [0.98202823 0.09257939 0.7001296  0.68028618 0.08915293]
 [0.22916754 0.70014636 0.44096407 0.17046712 0.58041678]
 [0.57938614 0.22062518 0.60942239 0.36309911 0.8700904 ]]


In [0]:
# transpose of a matrix

z = x.T

In [24]:
print(z)

[[0.3474321  0.98202823 0.22916754 0.57938614]
 [0.55340535 0.09257939 0.70014636 0.22062518]
 [0.12314722 0.7001296  0.44096407 0.60942239]
 [0.51713876 0.68028618 0.17046712 0.36309911]
 [0.45539885 0.08915293 0.58041678 0.8700904 ]]


In [25]:
# reshaping the array matrix

# 20 values are reshaped into  2 X 2 matrix

z.reshape(10,2)

array([[0.3474321 , 0.98202823],
       [0.22916754, 0.57938614],
       [0.55340535, 0.09257939],
       [0.70014636, 0.22062518],
       [0.12314722, 0.7001296 ],
       [0.44096407, 0.60942239],
       [0.51713876, 0.68028618],
       [0.17046712, 0.36309911],
       [0.45539885, 0.08915293],
       [0.58041678, 0.8700904 ]])

In [0]:
# rage array matrix

x = np.arange(5)

y = np.arange(5)

In [27]:
print(x)

[0 1 2 3 4]


In [28]:
print(y)

[0 1 2 3 4]


In [29]:
print("Additon of X and Y", x + y )

print("\nSubtration of X and Y", x - y )

print("\nmatrix of X and Y", x * y)

Additon of X and Y [0 2 4 6 8]

Subtration of X and Y [0 0 0 0 0]

matrix of X and Y [ 0  1  4  9 16]


In [30]:
 # scalar matrix
  
  print(x,x+1)

[0 1 2 3 4] [1 2 3 4 5]


In [31]:
 np.array([-1.7, -1.5, -0.2, 0.2, 1.5, 1.7, 2.0])

array([-1.7, -1.5, -0.2,  0.2,  1.5,  1.7,  2. ])

In [0]:
a = np.random.random((2,3)) * 10

In [33]:
print(a)

[[5.73356506 2.49747726 7.15752582]
 [0.84729444 1.91410355 4.56725892]]


In [34]:
np.floor(a)

array([[5., 2., 7.],
       [0., 1., 4.]])

In [35]:
# inner product

u = [1,2,3]

v = [-1,2,4]

np.inner(u,v)

15

In [36]:
# outer product

np.outer(u,v)

array([[-1,  2,  4],
       [-2,  4,  8],
       [-3,  6, 12]])

In [37]:
a = np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [38]:
b = np.ones((3,2))
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [39]:
# dot product
np.dot(a,b)

array([[3., 3.],
       [3., 3.]])

In [40]:
# dot product of transpose

np.dot(a.T,b.T)

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [41]:
# sum of matrix values

a.sum()

6.0

In [42]:
# max value in marix

a.max()

1.0

In [43]:
a.sum(axis= 0)

array([2., 2., 2.])

In [44]:
a.sum(axis= 1)

array([3., 3.])